using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace _08_WPF_Controls_1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DockPanel dp = new DockPanel();
            TextBlock t1 = new TextBlock();
            t1.Background = Brushes.Black;
            t1.Text = " 1 ";
            t1.Foreground = Brushes.White;
            dp.Children.Add(t1);
            DockPanel.SetDock(t1, Dock.Left);
            TextBlock t2 = new TextBlock();
            t2.Background = Brushes.Black;
            t2.Foreground = Brushes.White;
            t2.Text = " 2 ";
            dp.Children.Add(t2);
            DockPanel.SetDock(t2, Dock.Bottom);
            TextBlock t3 = new TextBlock();
            t3.Background = Brushes.Black;
            t3.Foreground = Brushes.White;
            t3.Text = " 3 ";
            dp.Children.Add(t3);
            DockPanel.SetDock(t3, Dock.Right);
            TextBlock t4 = new TextBlock();
            t4.Background = Brushes.White;
            t4.Text = " 4 ";
            dp.Children.Add(t4);
            DockPanel.SetDock(t4, Dock.Left);
            TextBlock t5 = new TextBlock();
            t5.Background = Brushes.Black;
            t5.Foreground = Brushes.White;
            t5.Text = " 5 ";
            dp.Children.Add(t5);
            DockPanel.SetDock(t5, Dock.Top);
            TextBlock t6 = new TextBlock();
            t6.Background = Brushes.White;
            t6.Text = " 6 ";
            dp.Children.Add(t6);
            DockPanel.SetDock(t6, Dock.Bottom);
            TextBlock t7 = new TextBlock();
            t7.Background = Brushes.White;
            //t7.Foreground = Brushes.White;
            t7.Text = " 7 ";
            dp.Children.Add(t7);
            DockPanel.SetDock(t7, Dock.Right);
            TextBlock t8 = new TextBlock();
            t8.Background = Brushes.Black;
            t8.Foreground = Brushes.White;
            t8.Text = " 8 ";
            dp.Children.Add(t8);
            DockPanel.SetDock(t8, Dock.Left);
            TextBlock t9 = new TextBlock();
            t9.Background = Brushes.White;
            t9.Text = " 9 ";
            dp.Children.Add(t9);
            DockPanel.SetDock(t9, Dock.Top);
            TextBlock t10 = new TextBlock();
            t10.Background = Brushes.Black;
            t10.Foreground = Brushes.White;
            t10.Text = " 10 ";
            dp.Children.Add(t10);
            DockPanel.SetDock(t10, Dock.Bottom);
            TextBlock t11 = new TextBlock();
            t11.Background = Brushes.Black;
            t11.Foreground = Brushes.White;
            t11.Text = " 11 ";
            dp.Children.Add(t11);
            DockPanel.SetDock(t11, Dock.Right);
            TextBlock t12 = new TextBlock();
            t12.Background = Brushes.White;
            //t12.Foreground = Brushes.White;
            t12.Text = "12";
            dp.Children.Add(t12);
            DockPanel.SetDock(t12, Dock.Left);
            TextBlock t13 = new TextBlock();
            t13.Background = Brushes.Black;
            t13.Foreground = Brushes.White;
            t13.Text = " 13 ";
            dp.Children.Add(t13);
            DockPanel.SetDock(t13, Dock.Top);
            TextBlock t14 = new TextBlock();
            t14.Background = Brushes.White;
            t14.Text = " 14 ";
            dp.Children.Add(t14);
            DockPanel.SetDock(t14, Dock.Bottom);
            TextBlock t15 = new TextBlock();
            t15.Background = Brushes.Black;
            t15.Foreground = Brushes.White;
            t15.Text = " 15 ";
            dp.Children.Add(t15);
            DockPanel.SetDock(t15, Dock.Left);
            TextBlock t16 = new TextBlock();
            t16.Background = Brushes.White;
            t16.Text = " 16 ";
            dp.Children.Add(t16);
            DockPanel.SetDock(t16, Dock.Right);
            TextBlock t17 = new TextBlock();
            t17.Background = Brushes.White;
            t17.Text = " 17 ";
            dp.Children.Add(t17);
            DockPanel.SetDock(t17, Dock.Top);
            TextBlock t18 = new TextBlock();
            t18.Background = Brushes.Black;
            t18.Foreground = Brushes.White;
            t18.Text = " 18 ";
            dp.Children.Add(t18);
            DockPanel.SetDock(t18, Dock.Bottom);
            TextBlock t19 = new TextBlock();
            t19.Background = Brushes.Black;
            t19.Foreground = Brushes.White;
            t19.Text = " 19 ";
            dp.Children.Add(t19);
            DockPanel.SetDock(t19, Dock.Right);
            TextBlock t20 = new TextBlock();
            t20.Background = Brushes.White;
            t20.Text = " 20 ";
            dp.Children.Add(t20);
            DockPanel.SetDock(t20, Dock.Left);
            TextBlock t21 = new TextBlock();
            t21.Background = Brushes.Black;
            t21.Foreground = Brushes.White;
            t21.Text = " 21 ";
            dp.Children.Add(t21);
            DockPanel.SetDock(t21, Dock.Top);
            TextBlock t22 = new TextBlock();
            t22.Background = Brushes.White;
            t22.Text = " 22 ";
            dp.Children.Add(t22);
            DockPanel.SetDock(t22, Dock.Bottom);
            TextBlock t23 = new TextBlock();
            t23.Background = Brushes.Black;
            t23.Foreground = Brushes.White;
            t23.Text = " 23 ";
            dp.Children.Add(t23);
            DockPanel.SetDock(t23, Dock.Left);
            TextBlock t24 = new TextBlock();
            t24.Background = Brushes.White;
            t24.Text = " 24 ";
            dp.Children.Add(t24);
            DockPanel.SetDock(t24, Dock.Right);
            TextBlock t25 = new TextBlock();
            t25.Background = Brushes.Black;
            t25.Foreground = Brushes.White;
            t25.Text = " 25 ";
            dp.Children.Add(t25);
            DockPanel.SetDock(t25, Dock.Bottom);
            TextBlock t26 = new TextBlock();
            t26.Background = Brushes.White;
            t26.Text = " 26 ";
            dp.Children.Add(t26);
            DockPanel.SetDock(t26, Dock.Top);

            Content = dp;
        }
    }
}
